### ISSUE TITLE
Druid 27.0 release planning

### ISSUE THREAD

**Issue by 2bethere** [apache/druid#14386]
This issue should cover things we want to land for the upcoming Druid 27 release and to coordinate any dependencies/reviews/docs and testing.

## Milestone tracking
**ETA for code free is July 7th, 2023**
https://github.com/apache/druid/milestone/51

Basing this on 
- #14157 

## Features
- [ ] Concurrent compaction + ingestion (--> Moving to Druid 28)
- [ ] Window functions (Experimental)
- [ ] Cold-tier/Async query (Experimental)
- [ ] Simplify segment balancing for improved stability
- [ ] Schemaless ingestion (GA)

## Dependency changes
- Hadoop 3 as the default build (#14301 )
- Hadoop 2 deprecation (Announcement, with depreciation targeting Druid 28)
- Update to Calcite 1.34 or later (#13532 --> Moving to Druid 28)

## Bug fixes and paying down tech debts
- Adding SQL null by default mode wrapper for future releases 
  * #14154 
  * #14142)
- Official support for jdk 17 (#14384)
- [bug fixes](https://github.com/apache/druid/pulls?q=is%3Apr+label%3ABug+milestone%3A27.0+)

**Comment by 2bethere** [comment]
@techdocsmith FYI
